<map version="1.0.1">
<!--
Generated by NB Mind Map Plugin (https://github.com/raydac/netbeans-mmd-plugin)
2022-09-04 22:51:16.343
-->
 <node CREATED="1662299476343" MODIFIED="1662299476343" COLOR="#FFFFFF" BACKGROUND_COLOR="#031A31"   ID="mmlink65" TEXT="Root topic"  LINK="https://appstew.github.io">
  <edge WIDTH="thin"/>  <richcontent TYPE="NOTE"><html><head></head><body><p><pre>note added</pre></p></body></html></richcontent>
  <node CREATED="1662299476343" MODIFIED="1662299476343" COLOR="#000000" BACKGROUND_COLOR="#B1BFCC" POSITION="right" ID="mmlink6565" TEXT="child01" >
   <edge WIDTH="thin"/>  </node>
  <node CREATED="1662299476343" MODIFIED="1662299476343" COLOR="#000000" BACKGROUND_COLOR="#B1BFCC" POSITION="right" ID="mmlink6566" TEXT="child03" >
   <edge WIDTH="thin"/>   <node CREATED="1662299476343" MODIFIED="1662299476343" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656665" TEXT="child04" >
    <edge WIDTH="thin"/>   </node>
  </node>
  <node CREATED="1662299476343" MODIFIED="1662299476343" COLOR="#000000" BACKGROUND_COLOR="#B1BFCC" POSITION="right" ID="mmlink6567" TEXT="child02"  LINK="#mmlink6565">
   <edge WIDTH="thin"/>  </node>
 </node>
</map>